In [9]:
#Exercise 8.1
#a) float from 0.0 to 1.0 step 0.1, shape=(11,),
import numpy as np
x=np.arange(0.0,1.1,0.1,dtype=float)
print(x)
np.shape(x)

[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1. ]


(11,)

In [11]:
#b)int zeros (1 byte) with shape=(5,6),
y = np.zeros((5, 6), dtype=int)
np.shape(y)

(5, 6)

In [31]:
#c)complex with shape=(9,), powers of x = complex(0, 1): 1, x, x**2, ..., x**8.
out = complex(0,1)**np.arange(9)
print(out)

[ 1.+0.j  0.+1.j -1.+0.j -0.-1.j  1.+0.j  0.+1.j -1.+0.j -0.-1.j  1.+0.j]


In [20]:
# Exercise 8.2
#a) Create an arbitrary one dimensional array called v1.
v1=np.arange(0,10,1)
print(v1)

#b)Create a new array v2 which consists of the odd indices of v1.
v2=v1[1::2]
print(v2)

#c) Create a new array v3 in backwards ordering from v1.
v3=v1[::-1]
print(v3)

[0 1 2 3 4 5 6 7 8 9]
[1 3 5 7 9]
[9 8 7 6 5 4 3 2 1 0]


In [30]:
# Exercise 8.3
#a) Create a two dimensional array called m1, shape=(4,5)
m1 = np.arange(20).reshape((4,5))
print(m1)

#b)Create a new array m2 from m1, in which the elements of each row are in reverse order.
m2= np.flip(m1, axis=1)
print(m2)

#c)Create a new array m3 from m1, in which the elements of each column are in reverse order.
m3= np.flip(m1, axis=0)
print(m3)

#d) Cut of the first and last row and the first and last column of m1.
data=np.delete(m1, [0,3], 0)
data1=np.delete(data,[0,4],1)
print(data1)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
[[ 4  3  2  1  0]
 [ 9  8  7  6  5]
 [14 13 12 11 10]
 [19 18 17 16 15]]
[[15 16 17 18 19]
 [10 11 12 13 14]
 [ 5  6  7  8  9]
 [ 0  1  2  3  4]]
[[ 6  7  8]
 [11 12 13]]
